name: Deploy Alphakid app
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run Testing
    runs-on: ubuntu-latest
    steps:
      - name: Get The Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-dependencies-cache-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Run Test Cases
        run: npm run test
